"""The head's mouth as one table: config/face.json's parameters, expressions and events.

The mouth on the head's 1.9" screen is procedural: a handful of numbers (width, opening, corner
lift, teeth, a wave along it, ...) draw it, and an expression is nothing but a full set of them.
The firmware tweens every number on its own, so any expression turns smoothly into any other,
and the speech level ('M' frames) opens whatever expression is showing. Three readers share the
table: the firmware (``firmware/head_esp32/src/face_table.h``), its desktop simulator
(``firmware/head_esp32/sim/face_table.js``) and the board's head server, which turns names into
the ids the wire carries and robot events into expressions. The two generated files are written
from the JSON by this module, and a unit test refuses a stale copy::

    uv run python -m pepin.face --write     regenerate both files after editing config/face.json
    uv run python -m pepin.face --check     exit 1 when either file is stale
    uv run python -m pepin.face             the expressions and events, one per line
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[2]
FIRMWARE = REPO / "firmware" / "head_esp32"
HEADER = FIRMWARE / "src" / "face_table.h"
SCRIPT = FIRMWARE / "sim" / "face_table.js"
FACE_FILE = "face.json"
GENERATED = "Generated by `uv run python -m pepin.face --write` from config/face.json; do not edit."


@dataclass(frozen=True)
class FaceParam:
    """One number of the mouth: its neutral value, its range and what it means."""

    name: str
    default: float
    lo: float
    hi: float
    note: str


@dataclass(frozen=True)
class Expression:
    """A named full set of parameter values, in the table's parameter order."""

    name: str
    values: tuple[float, ...]
    note: str


@dataclass(frozen=True)
class FaceEvent:
    """What a robot event shows: an expression, how long (None: until replaced or cleared) and
    how strongly (1.0 the expression itself, 0.5 halfway from neutral)."""

    expression: str
    hold_s: float | None
    intensity: float


@dataclass(frozen=True)
class FaceTable:
    """config/face.json, checked: the parameters, the expressions by id, the events."""

    params: tuple[FaceParam, ...]
    expressions: tuple[Expression, ...]
    events: dict[str, FaceEvent]
    geometry: dict[str, float]
    colors: dict[str, str]
    timing: dict[str, float]
    screen: dict[str, int]

    @property
    def names(self) -> tuple[str, ...]:
        """The expressions' names, by id."""
        return tuple(e.name for e in self.expressions)

    def id_of(self, name: str) -> int:
        """The wire id of an expression; ``KeyError`` naming the known ones otherwise."""
        try:
            return self.names.index(name)
        except ValueError:
            known = ", ".join(self.names)
            raise KeyError(f"no expression {name!r}; the face knows {known}") from None

    def event(self, name: str) -> FaceEvent:
        """What the robot event ``name`` shows; ``KeyError`` naming the known events otherwise."""
        try:
            return self.events[name]
        except KeyError:
            known = ", ".join(self.events)
            raise KeyError(f"no face event {name!r}; the table has {known}") from None


def load_face_table(path: str | Path | None = None) -> FaceTable:
    """config/face.json (or ``path``) checked: every value inside its parameter's range, every
    expression and event naming known things; ``ValueError`` saying what is wrong."""
    if path is None:
        from pepin.deployment import config_file

        path = config_file(FACE_FILE)
    data = json.loads(Path(path).read_text())
    return parse_face_table(data)


def parse_face_table(data: dict[str, Any]) -> FaceTable:
    """The table from config/face.json's parsed content (see :func:`load_face_table`)."""
    params = []
    for name, spec in data["params"].items():
        lo, hi = (float(v) for v in spec["range"])
        default = float(spec["default"])
        if not lo <= default <= hi:
            raise ValueError(f"param {name}: default {default} outside {lo}..{hi}")
        params.append(FaceParam(name, default, lo, hi, str(spec.get("note", ""))))
    by_name = {p.name: p for p in params}
    expressions = []
    for entry in data["expressions"]:
        name = str(entry["name"])
        if not re.fullmatch(r"[a-z][a-z_]*", name):
            raise ValueError(f"expression {name!r}: a lower_snake_case name")
        given = dict(entry.get("params", {}))
        unknown = sorted(set(given) - set(by_name))
        if unknown:
            raise ValueError(f"expression {name}: unknown params {', '.join(unknown)}")
        values = []
        for param in params:
            value = float(given.get(param.name, param.default))
            if not param.lo <= value <= param.hi:
                raise ValueError(
                    f"expression {name}: {param.name} {value} outside {param.lo}..{param.hi}"
                )
            values.append(value)
        expressions.append(Expression(name, tuple(values), str(entry.get("note", ""))))
    names = [e.name for e in expressions]
    if len(set(names)) != len(names):
        raise ValueError("expression names repeat")
    if not names or names[0] != "neutral":
        raise ValueError("expression 0 is neutral: the face the firmware boots into")
    if "sleepy" not in names:
        raise ValueError("the firmware falls asleep into 'sleepy': the table needs it")
    events = {}
    for event, spec in data.get("events", {}).items():
        expression = str(spec["name"])
        if expression not in names:
            raise ValueError(f"event {event}: no expression {expression!r}")
        hold = spec.get("hold_s")
        intensity = float(spec.get("intensity", 1.0))
        if hold is not None and not float(hold) > 0.0:
            raise ValueError(f"event {event}: hold_s is positive or null")
        if not 0.0 <= intensity <= 1.0:
            raise ValueError(f"event {event}: intensity in 0..1")
        events[event] = FaceEvent(expression, None if hold is None else float(hold), intensity)
    colors = {k: str(v) for k, v in data["colors"].items() if k != "note"}
    for key, color in colors.items():
        if not re.fullmatch(r"#[0-9A-Fa-f]{6}", color):
            raise ValueError(f"color {key}: #RRGGBB, not {color!r}")
    return FaceTable(
        params=tuple(params),
        expressions=tuple(expressions),
        events=events,
        geometry={k: float(v) for k, v in data["geometry"].items() if k != "note"},
        colors=colors,
        timing={k: float(v) for k, v in data["timing"].items() if k != "note"},
        screen={k: int(v) for k, v in data["screen"].items() if k != "note"},
    )


def rgb565(color: str) -> int:
    """``#RRGGBB`` as the panel's 16-bit RGB565."""
    r, g, b = (int(color[i : i + 2], 16) for i in (1, 3, 5))
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def _camel(name: str) -> str:
    """``max_open_px`` -> ``MaxOpenPx``."""
    return "".join(part.capitalize() for part in name.split("_"))


def _float(value: float) -> str:
    """A C++ float literal."""
    text = repr(float(value))
    return (text if "." in text or "e" in text else text + ".0") + "f"


def render_header(table: FaceTable) -> str:
    """face_table.h: the table as C++ constants for the firmware (and its native tests)."""
    n = len(table.params)
    lows = ", ".join(_float(p.lo) for p in table.params)
    highs = ", ".join(_float(p.hi) for p in table.params)
    lines = [
        f"// {GENERATED}",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "namespace face {",
        "",
        f"constexpr int kParamCount = {n};",
        "enum Param : uint8_t {",
        *(f"  k{_camel(p.name)} = {i},  // {p.note}" for i, p in enumerate(table.params)),
        "};",
        f"constexpr float kParamMin[kParamCount] = {{{lows}}};",
        f"constexpr float kParamMax[kParamCount] = {{{highs}}};",
        "",
        f"constexpr int kExpressionCount = {len(table.expressions)};",
        "constexpr const char* kExpressionNames[kExpressionCount] = {",
        *(f'  "{e.name}",' for e in table.expressions),
        "};",
        "constexpr float kExpressions[kExpressionCount][kParamCount] = {",
        *(
            f"  {{{', '.join(_float(v) for v in e.values)}}},  // {i} {e.name}"
            for i, e in enumerate(table.expressions)
        ),
        "};",
        f"constexpr int kNeutral = {table.id_of('neutral')};",
        f"constexpr int kSleepy = {table.id_of('sleepy')};",
        "",
        "// screen",
        *(f"constexpr int kScreen{_camel(k)} = {v};" for k, v in table.screen.items()),
        "",
        "// geometry: what each parameter at 1.0 means",
        *(f"constexpr float k{_camel(k)} = {_float(v)};" for k, v in table.geometry.items()),
        "",
        "// timing",
        *(f"constexpr float k{_camel(k)} = {_float(v)};" for k, v in table.timing.items()),
        "",
        "// colors, RGB565",
        *(
            f"constexpr uint16_t kColor{_camel(k)} = 0x{rgb565(v):04X};  // {v}"
            for k, v in table.colors.items()
        ),
        "",
        "}  // namespace face",
        "",
    ]
    return "\n".join(lines)


def render_script(table: FaceTable) -> str:
    """face_table.js: the same table for the simulator (a plain script: it loads from file://)."""
    payload = {
        "params": [
            {"name": p.name, "default": p.default, "min": p.lo, "max": p.hi, "note": p.note}
            for p in table.params
        ],
        "expressions": [
            {"name": e.name, "values": list(e.values), "note": e.note} for e in table.expressions
        ],
        "events": {
            k: {"name": v.expression, "hold_s": v.hold_s, "intensity": v.intensity}
            for k, v in table.events.items()
        },
        "screen": table.screen,
        "geometry": table.geometry,
        "timing": table.timing,
        "colors": table.colors,
        "rgb565": {k: rgb565(v) for k, v in table.colors.items()},
    }
    body = json.dumps(payload, indent=1, ensure_ascii=False)
    return (
        f"// {GENERATED}\n"
        f"const FACE_TABLE = {body};\n"
        'if (typeof module !== "undefined") module.exports = FACE_TABLE;\n'
    )


def generated(table: FaceTable) -> dict[Path, str]:
    """Each generated file and the text it must hold."""
    return {HEADER: render_header(table), SCRIPT: render_script(table)}


def stale(table: FaceTable) -> list[Path]:
    """The generated files whose text differs from what the table renders."""
    return [
        path
        for path, text in generated(table).items()
        if not path.is_file() or path.read_text() != text
    ]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="The head's face table (config/face.json).")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="regenerate the firmware/sim tables")
    mode.add_argument("--check", action="store_true", help="exit 1 when a generated file is stale")
    args = parser.parse_args(argv)
    table = load_face_table(REPO / "config" / FACE_FILE)
    if args.write:
        for path, text in generated(table).items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(f"wrote {path.relative_to(REPO)}")
        return 0
    if args.check:
        old = stale(table)
        for path in old:
            print(f"stale: {path.relative_to(REPO)} (uv run python -m pepin.face --write)")
        return 1 if old else 0
    for i, expression in enumerate(table.expressions):
        print(f"{i:2d} {expression.name:<11} {expression.note}")
    for name, event in table.events.items():
        hold = "held" if event.hold_s is None else f"{event.hold_s:g} s"
        print(f"   {name:<15} -> {event.expression} ({hold}, x{event.intensity:g})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
