#!/usr/bin/env python3
"""The nodes' feature-flag tables (pepin.flags) rendered for people and for ros/flags.sh.

A node with live switches declares them once, in the module-level ``FLAGS`` table of
ros/pepin_bringup/pepin_bringup/<node>.py; this tool reads those tables from the sources
(:func:`pepin.flags.load_table`: no ROS, no robot) and answers:

    ros/tools/flags_doc.py                 rewrite the "Feature flags" section of ros/README.md
    ros/tools/flags_doc.py --check         exit 1 when that section is stale (the unit test)
    ros/tools/flags_doc.py nodes           the nodes that carry a table, one per line
    ros/tools/flags_doc.py where NODE      "laptop pepin-vslam" / "board pepin-ros": NODE's home
    ros/tools/flags_doc.py flag NODE FLAG  one flag's kind and help; exit 2 when there is none
    ros/tools/flags_doc.py list NODE       NODE's flags with their current values, read from a
                                           ``ros2 param dump /NODE`` on stdin (empty: node down)
    ros/tools/flags_doc.py value NODE FLAG VALUE
                                           VALUE checked by the flag and printed the way
                                           ``ros2 param set`` reads it (a double as 3.0, a
                                           string safe from YAML); exit 2 with the reason

Runs on the laptop from the repository's environment (``uv run``), never inside a container.
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

import yaml

from pepin.deployment import node_host
from pepin.flags import COLUMNS, Flag, FlagSet, load_table, markdown_table

REPO = Path(__file__).resolve().parents[2]
NODES_DIR = REPO / "ros/pepin_bringup/pepin_bringup"
README = REPO / "ros/README.md"
HEADING = "## Feature flags"
INTRO = """\
Every behaviour that can be switched is a live parameter of the node that owns it, declared
once in that node's `FLAGS` table (`pepin.flags`, declared to ROS by
`pepin_bringup.node_kit.Switches`) with its kind, default and description, checked by kind on
every change, and printed in the node's report line (CLAUDE.md rule 19). `ros/flags.sh list
[NODE]` shows them with their current values, `ros/flags.sh set NODE FLAG VALUE` changes one
live (a value the flag refuses is refused with the reason, before any host is touched),
`ros/flags.sh get NODE FLAG` reads one; the script execs into whichever container the node
runs in. A change lives until the node restarts; a default changes in the table. This table is
generated by `ros/tools/flags_doc.py` (a unit test keeps it current)."""


def has_table(path: Path, name: str = "FLAGS") -> bool:
    """Whether the module at ``path`` assigns ``name`` at module level."""
    module = ast.parse(path.read_text(), filename=str(path))
    return any(
        isinstance(node, ast.Assign)
        and any(isinstance(t, ast.Name) and t.id == name for t in node.targets)
        for node in module.body
    )


def tables() -> dict[str, FlagSet]:
    """Every node's table by node name, in file order."""
    return {
        path.stem: load_table(path) for path in sorted(NODES_DIR.glob("*.py")) if has_table(path)
    }


def section() -> str:
    """The README section: the heading, the introduction, one table over every node."""
    rows = [[f"`{node}`", *row] for node, flags in tables().items() for row in flags.rows()]
    return f"{HEADING}\n\n{INTRO}\n\n{markdown_table(('node', *COLUMNS), rows)}\n"


def readme_with(text: str, body: str, before: str = "## Build and run") -> str:
    """``text`` with its feature-flags section replaced by ``body`` — the heading up to the
    next ``## `` heading — or, when it has none, with ``body`` inserted before the ``before``
    heading (at the end when that is missing too)."""
    start = text.find(HEADING)
    if start >= 0:
        end = text.find("\n## ", start + len(HEADING))
        end = len(text) if end < 0 else end + 1
        return text[:start] + body + "\n" + text[end:] if end < len(text) else text[:start] + body
    at = text.find(before)
    if at < 0:
        return text.rstrip("\n") + "\n\n" + body
    return text[:at] + body + "\n" + text[at:]


def current_values(dump: str) -> dict[str, object]:
    """The parameters of a ``ros2 param dump /node`` (its YAML: the node, ``ros__parameters``,
    the values); empty when the dump is empty or not that."""
    try:
        loaded = yaml.safe_load(dump)
    except yaml.YAMLError:
        return {}
    if not isinstance(loaded, dict) or len(loaded) != 1:
        return {}
    (block,) = loaded.values()
    params = block.get("ros__parameters") if isinstance(block, dict) else None
    return dict(params) if isinstance(params, dict) else {}


def listing(node: str, flags: FlagSet, dump: str) -> str:
    """The node's flags as lines for a terminal: name, kind, current value (``?`` when the node
    did not answer, ``unset`` when it runs without the flag), description."""
    values = current_values(dump)
    rows = []
    for flag in flags:
        if not values:
            current = "?"
        elif flag.name not in values:
            current = "unset"
        else:
            try:
                current = flag.render(flag.parse(values[flag.name]))
            except ValueError:
                current = repr(values[flag.name])
        rows.append((f"{node}/{flag.name}", flag.kind_text(), current, flag.description))
    widths = [max(len(r[i]) for r in rows) for i in range(3)]
    lines = [
        f"{r[0]:<{widths[0]}}  {r[1]:<{widths[1]}}  {r[2]:<{widths[2]}}  {r[3]}".rstrip()
        for r in rows
    ]
    if not values:
        lines.append(f"({node} did not answer a parameter dump: is it up?)")
    return "\n".join(lines)


def yaml_literal(flag: Flag, value: object) -> str:
    """``value`` (already the flag's) as the one word ``ros2 param set`` turns back into it:
    YAML, so a double keeps its point, a string that YAML would read as something else is
    tagged ``!!str``, an empty string is quoted."""
    wire = flag.wire(value)
    if isinstance(wire, bool):
        return "true" if wire else "false"
    if isinstance(wire, int):
        return str(wire)
    if isinstance(wire, float):
        return repr(float(wire))
    text = str(wire)
    if text == "":
        return "''"
    return text if yaml.safe_load(text) == text else f"!!str {text}"


def _refuse(reason: str) -> None:
    """A request this tool cannot honour: the reason on stderr, exit status 2."""
    print(reason, file=sys.stderr)
    sys.exit(2)


def _node(name: str) -> tuple[str, FlagSet]:
    known = tables()
    node = name.lstrip("/")
    if node not in known:
        _refuse(f"{node}: no node with a flags table; the nodes are {', '.join(known)}")
    return node, known[node]


def main(argv: list[str]) -> int:
    """The verbs of the module docstring; 2 for a bad request, 1 for a stale README."""
    verb = argv[0] if argv else ""
    if verb in ("", "--check"):
        text = README.read_text()
        fresh = readme_with(text, section())
        if verb == "--check":
            if fresh != text:
                print(f"{README}: the Feature flags section is stale; run ros/tools/flags_doc.py")
                return 1
            return 0
        README.write_text(fresh)
        print(f"{README}: Feature flags section written")
        return 0
    if verb == "nodes":
        print("\n".join(tables()))
        return 0
    if verb == "where" and len(argv) == 2:
        node, _ = _node(argv[1])
        print(*node_host(node))
        return 0
    if verb == "flag" and len(argv) == 3:
        node, flags = _node(argv[1])
        if argv[2] not in flags:
            _refuse(f"{node}: no flag {argv[2]}; the flags are {', '.join(flags.names)}")
        flag = flags.flag(argv[2])
        print(f"{node}/{flag.name}: {flag.kind_text()}, default {flag.render(flag.default)}")
        if flag.help():
            print(flag.help())
        return 0
    if verb == "list" and len(argv) == 2:
        node, flags = _node(argv[1])
        print(listing(node, flags, sys.stdin.read() if not sys.stdin.isatty() else ""))
        return 0
    if verb == "value" and len(argv) == 4:
        node, flags = _node(argv[1])
        if argv[2] not in flags:
            _refuse(f"{node}: no flag {argv[2]}; the flags are {', '.join(flags.names)}")
        flag = flags.flag(argv[2])
        if not flag.live:
            _refuse(f"{node}/{flag.name}: not live, set at the next start")
        try:
            print(yaml_literal(flag, flag.parse(argv[3])))
        except ValueError as exc:
            _refuse(str(exc))
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
