// Generated by `uv run python -m pepin.face --write` from config/face.json; do not edit.
const FACE_TABLE = {
 "params": [
  {
   "name": "width",
   "default": 0.46,
   "min": 0.08,
   "max": 0.95,
   "note": "the mouth's width, a share of the screen's"
  },
  {
   "name": "open",
   "default": 0.0,
   "min": 0.0,
   "max": 1.0,
   "note": "the opening at the middle, a share of max_open_px"
  },
  {
   "name": "smile",
   "default": 0.12,
   "min": -1.0,
   "max": 1.0,
   "note": "the corners lifted (+) or dropped (-), smile_px at 1"
  },
  {
   "name": "upper",
   "default": 0.5,
   "min": 0.0,
   "max": 1.0,
   "note": "the share of the opening above the mouth's line: 0 keeps the upper lip on the line (a D-shaped grin)"
  },
  {
   "name": "corner_exp",
   "default": 2.0,
   "min": 1.0,
   "max": 12.0,
   "note": "the opening's profile: 1.2 a lens with pointed corners, 2 an ellipse, 8 a rounded rectangle"
  },
  {
   "name": "teeth",
   "default": 0.0,
   "min": 0.0,
   "max": 1.0,
   "note": "0 none, 0.5 the upper row, 1 both rows meeting at the bite (clenched)"
  },
  {
   "name": "wave",
   "default": 0.0,
   "min": 0.0,
   "max": 1.0,
   "note": "a wave along the mouth, wave_px at 1: worried wobble or the zigzag"
  },
  {
   "name": "wave_n",
   "default": 2.0,
   "min": 0.5,
   "max": 12.0,
   "note": "wave periods across the mouth"
  },
  {
   "name": "wave_sharp",
   "default": 0.0,
   "min": 0.0,
   "max": 1.0,
   "note": "0 a sine, 1 a zigzag"
  },
  {
   "name": "wave_speed",
   "default": 0.0,
   "min": -3.0,
   "max": 3.0,
   "note": "the wave crawls along the mouth, periods per second"
  },
  {
   "name": "asym",
   "default": 0.0,
   "min": -1.0,
   "max": 1.0,
   "note": "the right corner (as seen) up (+) and the left down, asym_px at 1"
  },
  {
   "name": "shift_x",
   "default": 0.0,
   "min": -1.0,
   "max": 1.0,
   "note": "the mouth moved sideways, shift_x_px at 1 (+ right as seen)"
  },
  {
   "name": "shift_y",
   "default": 0.0,
   "min": -1.0,
   "max": 1.0,
   "note": "the mouth moved down (+), shift_y_px at 1"
  },
  {
   "name": "thick",
   "default": 0.45,
   "min": 0.0,
   "max": 1.0,
   "note": "the lip line, thick_min_px..thick_max_px"
  },
  {
   "name": "breathe",
   "default": 0.15,
   "min": 0.0,
   "max": 1.0,
   "note": "a slow idle breath of the width and the opening (breathe_hz)"
  },
  {
   "name": "drift",
   "default": 0.0,
   "min": 0.0,
   "max": 1.0,
   "note": "a slow idle drift sideways (drift_hz), shift_x_px/3 at 1"
  }
 ],
 "expressions": [
  {
   "name": "neutral",
   "values": [
    0.46,
    0.0,
    0.12,
    0.5,
    2.0,
    0.0,
    0.0,
    2.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.45,
    0.15,
    0.0
   ],
   "note": "the resting mouth: a short, slightly lifted line"
  },
  {
   "name": "smile",
   "values": [
    0.54,
    0.0,
    0.62,
    0.5,
    2.0,
    0.0,
    0.0,
    2.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.5,
    0.15,
    0.0
   ],
   "note": "a closed smile"
  },
  {
   "name": "happy",
   "values": [
    0.6,
    0.42,
    0.7,
    0.08,
    2.4,
    0.32,
    0.0,
    2.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.45,
    0.25,
    0.0
   ],
   "note": "an open D-shaped smile with the upper teeth showing (arrived)"
  },
  {
   "name": "grin",
   "values": [
    0.7,
    0.3,
    0.45,
    0.2,
    3.0,
    0.5,
    0.0,
    2.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.45,
    0.15,
    0.0
   ],
   "note": "a wide grin, the upper row of teeth"
  },
  {
   "name": "clenched",
   "values": [
    0.66,
    0.36,
    0.05,
    0.5,
    7.0,
    1.0,
    0.0,
    2.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.4,
    0.0,
    0.0
   ],
   "note": "a grin with clenched teeth: effort, awkwardness"
  },
  {
   "name": "sad",
   "values": [
    0.44,
    0.0,
    -0.62,
    0.5,
    2.0,
    0.0,
    0.0,
    2.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.5,
    0.1,
    0.0
   ],
   "note": "the corners down (a goal failed)"
  },
  {
   "name": "worried",
   "values": [
    0.46,
    0.05,
    -0.28,
    0.5,
    1.6,
    0.0,
    0.35,
    2.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.45,
    0.1,
    0.0
   ],
   "note": "a wobbly, slightly open frown"
  },
  {
   "name": "surprised",
   "values": [
    0.2,
    0.62,
    0.0,
    0.5,
    2.0,
    0.0,
    0.0,
    2.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.55,
    0.3,
    0.0
   ],
   "note": "an O"
  },
  {
   "name": "thinking",
   "values": [
    0.3,
    0.0,
    -0.08,
    0.5,
    2.0,
    0.0,
    0.0,
    2.0,
    0.0,
    0.0,
    0.55,
    0.45,
    0.0,
    0.5,
    0.05,
    0.6
   ],
   "note": "a short skewed line off to the side, drifting (the LLM is working)"
  },
  {
   "name": "struggling",
   "values": [
    0.62,
    0.0,
    -0.1,
    0.5,
    2.0,
    0.0,
    0.7,
    7.0,
    1.0,
    1.2,
    0.0,
    0.0,
    0.0,
    0.45,
    0.0,
    0.0
   ],
   "note": "a crawling zigzag: a recovery, a slip, stuck"
  },
  {
   "name": "flat",
   "values": [
    0.42,
    0.0,
    0.0,
    0.5,
    2.0,
    0.0,
    0.0,
    2.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.4,
    0.0,
    0.0
   ],
   "note": "a dead-straight line: unimpressed, no comment"
  },
  {
   "name": "sleepy",
   "values": [
    0.16,
    0.07,
    0.0,
    0.5,
    2.0,
    0.0,
    0.0,
    2.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.35,
    1.0,
    0.0
   ],
   "note": "a small round mouth breathing slowly (the host is silent, the brain is away)"
  },
  {
   "name": "focused",
   "values": [
    0.3,
    0.0,
    0.0,
    0.5,
    2.0,
    0.0,
    0.0,
    2.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.65,
    0.05,
    0.0
   ],
   "note": "a short firm line (driving to a goal)"
  },
  {
   "name": "listening",
   "values": [
    0.26,
    0.1,
    0.2,
    0.5,
    2.0,
    0.0,
    0.0,
    2.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.45,
    0.2,
    0.0
   ],
   "note": "a small open, attentive mouth (someone speaks to the robot)"
  }
 ],
 "events": {
  "goal_accepted": {
   "name": "focused",
   "hold_s": null,
   "intensity": 1.0
  },
  "recovery": {
   "name": "struggling",
   "hold_s": 3.0,
   "intensity": 1.0
  },
  "arrived": {
   "name": "happy",
   "hold_s": 4.0,
   "intensity": 1.0
  },
  "goal_failed": {
   "name": "sad",
   "hold_s": 5.0,
   "intensity": 1.0
  },
  "goal_cancelled": {
   "name": "flat",
   "hold_s": 1.5,
   "intensity": 1.0
  },
  "listening": {
   "name": "listening",
   "hold_s": null,
   "intensity": 1.0
  },
  "thinking": {
   "name": "thinking",
   "hold_s": null,
   "intensity": 1.0
  },
  "speaking": {
   "name": "smile",
   "hold_s": null,
   "intensity": 0.6
  },
  "brain_lost": {
   "name": "sleepy",
   "hold_s": null,
   "intensity": 1.0
  }
 },
 "screen": {
  "width": 320,
  "height": 170,
  "rotation": 3
 },
 "geometry": {
  "max_open_px": 112.0,
  "smile_px": 38.0,
  "asym_px": 22.0,
  "wave_px": 13.0,
  "shift_x_px": 60.0,
  "shift_y_px": 28.0,
  "thick_min_px": 3.0,
  "thick_max_px": 14.0,
  "tooth_px": 18.0,
  "tooth_gap_px": 2.0,
  "speech_open": 0.55,
  "speech_narrow": 0.18,
  "breathe_hz": 0.25,
  "drift_hz": 0.33
 },
 "timing": {
  "transition_ms": 280.0,
  "host_silent_s": 3.0,
  "mouth_attack_s": 0.03,
  "mouth_release_s": 0.09,
  "mouth_stale_s": 0.25
 },
 "lipsync": {
  "window_s": 0.04,
  "floor_db": -48.0,
  "full_db": -15.0,
  "lead_s": 0.0,
  "start_latency_s": 0.12
 },
 "colors": {
  "background": "#000000",
  "lip": "#7FE8FF",
  "cavity": "#08313C",
  "teeth": "#F4FBFF",
  "text": "#D8F6FF",
  "accent": "#7FE8FF"
 },
 "rgb565": {
  "background": 0,
  "lip": 32607,
  "cavity": 2439,
  "teeth": 63455,
  "text": 57279,
  "accent": 32607
 }
};
if (typeof module !== "undefined") module.exports = FACE_TABLE;
