// Generated by `uv run python -m pepin.face --write` from config/face.json; do not edit.
#pragma once

#include <stdint.h>

namespace face {

constexpr int kParamCount = 16;
enum Param : uint8_t {
  kWidth = 0,  // the mouth's width, a share of the screen's
  kOpen = 1,  // the opening at the middle, a share of max_open_px
  kSmile = 2,  // the corners lifted (+) or dropped (-), smile_px at 1
  kUpper = 3,  // the share of the opening above the mouth's line: 0 keeps the upper lip on the line (a D-shaped grin)
  kCornerExp = 4,  // the opening's profile: 1.2 a lens with pointed corners, 2 an ellipse, 8 a rounded rectangle
  kTeeth = 5,  // 0 none, 0.5 the upper row, 1 both rows meeting at the bite (clenched)
  kWave = 6,  // a wave along the mouth, wave_px at 1: worried wobble or the zigzag
  kWaveN = 7,  // wave periods across the mouth
  kWaveSharp = 8,  // 0 a sine, 1 a zigzag
  kWaveSpeed = 9,  // the wave crawls along the mouth, periods per second
  kAsym = 10,  // the right corner (as seen) up (+) and the left down, asym_px at 1
  kShiftX = 11,  // the mouth moved sideways, shift_x_px at 1 (+ right as seen)
  kShiftY = 12,  // the mouth moved down (+), shift_y_px at 1
  kThick = 13,  // the lip line, thick_min_px..thick_max_px
  kBreathe = 14,  // a slow idle breath of the width and the opening (breathe_hz)
  kDrift = 15,  // a slow idle drift sideways (drift_hz), shift_x_px/3 at 1
};
constexpr float kParamMin[kParamCount] = {0.08f, 0.0f, -1.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.5f, 0.0f, -3.0f, -1.0f, -1.0f, -1.0f, 0.0f, 0.0f, 0.0f};
constexpr float kParamMax[kParamCount] = {0.95f, 1.0f, 1.0f, 1.0f, 12.0f, 1.0f, 1.0f, 12.0f, 1.0f, 3.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f};

constexpr int kExpressionCount = 14;
constexpr const char* kExpressionNames[kExpressionCount] = {
  "neutral",
  "smile",
  "happy",
  "grin",
  "clenched",
  "sad",
  "worried",
  "surprised",
  "thinking",
  "struggling",
  "flat",
  "sleepy",
  "focused",
  "listening",
};
constexpr float kExpressions[kExpressionCount][kParamCount] = {
  {0.46f, 0.0f, 0.12f, 0.5f, 2.0f, 0.0f, 0.0f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.45f, 0.15f, 0.0f},  // 0 neutral
  {0.54f, 0.0f, 0.62f, 0.5f, 2.0f, 0.0f, 0.0f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.5f, 0.4f, 0.0f},  // 1 smile
  {0.6f, 0.42f, 0.7f, 0.08f, 2.4f, 0.32f, 0.0f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.45f, 0.25f, 0.0f},  // 2 happy
  {0.7f, 0.3f, 0.45f, 0.2f, 3.0f, 0.5f, 0.0f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.45f, 0.15f, 0.0f},  // 3 grin
  {0.66f, 0.36f, 0.05f, 0.5f, 7.0f, 1.0f, 0.0f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.4f, 0.0f, 0.0f},  // 4 clenched
  {0.44f, 0.0f, -0.62f, 0.5f, 2.0f, 0.0f, 0.0f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.5f, 0.1f, 0.0f},  // 5 sad
  {0.46f, 0.05f, -0.28f, 0.5f, 1.6f, 0.0f, 0.35f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.45f, 0.1f, 0.0f},  // 6 worried
  {0.2f, 0.62f, 0.0f, 0.5f, 2.0f, 0.0f, 0.0f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.55f, 0.3f, 0.0f},  // 7 surprised
  {0.3f, 0.0f, -0.08f, 0.5f, 2.0f, 0.0f, 0.0f, 2.0f, 0.0f, 0.0f, 0.55f, 0.45f, 0.0f, 0.5f, 0.05f, 0.6f},  // 8 thinking
  {0.62f, 0.0f, -0.1f, 0.5f, 2.0f, 0.0f, 0.7f, 7.0f, 1.0f, 1.2f, 0.0f, 0.0f, 0.0f, 0.45f, 0.0f, 0.0f},  // 9 struggling
  {0.42f, 0.0f, 0.0f, 0.5f, 2.0f, 0.0f, 0.0f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.4f, 0.0f, 0.0f},  // 10 flat
  {0.16f, 0.07f, 0.0f, 0.5f, 2.0f, 0.0f, 0.0f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.35f, 1.0f, 0.0f},  // 11 sleepy
  {0.3f, 0.0f, 0.0f, 0.5f, 2.0f, 0.0f, 0.0f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.65f, 0.05f, 0.0f},  // 12 focused
  {0.26f, 0.1f, 0.2f, 0.5f, 2.0f, 0.0f, 0.0f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.45f, 0.2f, 0.0f},  // 13 listening
};
constexpr int kNeutral = 0;
constexpr int kSleepy = 11;

// screen
constexpr int kScreenWidth = 320;
constexpr int kScreenHeight = 170;
constexpr int kScreenRotation = 1;

// geometry: what each parameter at 1.0 means
constexpr float kMaxOpenPx = 112.0f;
constexpr float kSmilePx = 38.0f;
constexpr float kAsymPx = 22.0f;
constexpr float kWavePx = 13.0f;
constexpr float kShiftXPx = 60.0f;
constexpr float kShiftYPx = 28.0f;
constexpr float kThickMinPx = 3.0f;
constexpr float kThickMaxPx = 14.0f;
constexpr float kToothPx = 18.0f;
constexpr float kToothGapPx = 2.0f;
constexpr float kSpeechOpen = 0.55f;
constexpr float kSpeechNarrow = 0.18f;
constexpr float kBreatheHz = 0.25f;
constexpr float kDriftHz = 0.33f;

// timing
constexpr float kTransitionMs = 280.0f;
constexpr float kHostSilentS = 3.0f;
constexpr float kMouthAttackS = 0.03f;
constexpr float kMouthReleaseS = 0.09f;
constexpr float kMouthStaleS = 0.25f;

// idle: the face alive at rest
constexpr bool kIdleOn = true;
constexpr uint32_t kIdleExpressionMask = 0x00000003u;  // neutral, smile
constexpr float kIdleEveryMinS = 8.0f;
constexpr float kIdleEveryMaxS = 20.0f;
constexpr float kIdleSettleS = 3.0f;
constexpr float kIdleFadeS = 0.25f;
constexpr int kIdleGestureCount = 3;
constexpr float kIdleGestureWeight[kIdleGestureCount] = {2.0f, 2.0f, 1.0f};
constexpr float kIdleGestureDurationS[kIdleGestureCount] = {1.6f, 2.2f, 0.4f};
constexpr bool kIdleGestureMirror[kIdleGestureCount] = {false, true, false};
constexpr float kIdleGestures[kIdleGestureCount][kParamCount] = {
  {0.06f, 0.0f, 0.22f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f},  // grin
  {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.28f, 0.1f, 0.0f, 0.0f, 0.0f, 0.0f},  // tilt
  {-0.03f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.25f, 0.0f, 0.0f},  // blink
};

// colors, RGB565
constexpr uint16_t kColorBackground = 0x0000;  // #000000
constexpr uint16_t kColorLip = 0x7F5F;  // #7FE8FF
constexpr uint16_t kColorCavity = 0x0987;  // #08313C
constexpr uint16_t kColorTeeth = 0xF7DF;  // #F4FBFF
constexpr uint16_t kColorText = 0xDFBF;  // #D8F6FF
constexpr uint16_t kColorAccent = 0x7F5F;  // #7FE8FF

}  // namespace face
